<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Multiple Test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d51f1338-cf9c-4bdf-91be-446fa32c3f9a</testSuiteGuid>
   <testCaseLink>
      <guid>724c3595-54fe-4494-8a26-b49fd9795aec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ManualMode/Test2_ManualMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73b250c8-09a0-4091-b28a-45b23014d2dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e66296a-c565-4146-b1fe-a5659cfa96a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07a140e1-cae9-4019-ba0b-819e9ae07ac1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTest/Test5_DatadrivenTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c4e0379-fcb2-42b6-ac80-6bc6986f80cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea35a1f1-abce-4b8f-b294-ff06a4c707a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c890a3-fe31-4f1b-8ce5-2c66c641f201</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb26026b-7e2e-42b5-8541-e2273dca0cd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebTable/WebTable - Performing Action</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
