<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logoImage</name>
   <tag></tag>
   <elementGuidId>9375e4fe-39ab-4f1b-8a0d-c12f1ffb7bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imagetrgt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
